# -*- coding: utf-8 -*-
"""Movie Recommendation System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IzHYzaBCc2gziwMcm44R8-3S2hKw8tVx

# *Importing required Libraries*
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# *Importing Dataset*"""

df=pd.read_csv("/content/Movies Recommendation.csv")

"""# *Describing Data*"""

df.head()

df.info()

df.shape

df.columns

df_features=df[['Movie_Genre','Movie_Keywords','Movie_Spoken_Language','Movie_Production_Country','Movie_Cast']].fillna('')

df_features.shape

df_features

x=df_features['Movie_Cast'] +' '+ df_features['Movie_Genre'] +' '+ df_features['Movie_Keywords'] + ' '+ df_features['Movie_Production_Country'] + ' ' + df_features['Movie_Spoken_Language']

x.shape

"""# Get Feature Text Conversions to Tokens"""

from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
x=tf.fit_transform(x)
x.shape

print(x)

"""# Similarity Score using Cosine Similarity"""

from sklearn.metrics.pairwise import cosine_similarity
c=cosine_similarity(x)
c

c.shape

"""# Get recommendation based on your favourite movie selection"""

u=input("Enter your movie name:")

all_movies_title_list=df['Movie_Title'].tolist()

import difflib

Movie_recommendation=difflib.get_close_matches(u,all_movies_title_list)
print(Movie_recommendation)

close_match=Movie_recommendation[0]
print(close_match)

index=df[df.Movie_Title==close_match]['Movie_ID'].values[0]
print(index)

Recommendation_Score=list(enumerate(c[index]))
print(Recommendation_Score)

len(Recommendation_Score)

Sorted_Similar_Movies=sorted(Recommendation_Score,key=lambda x:x[1] ,reverse=True)
print(Sorted_Similar_Movies)

print('Top 30. movies suggested for you:')
i=1
for movie in Sorted_Similar_Movies:
  index=movie[0]
  title_from_index=df[df.index==index]['Movie_Title'].values[0]
  if (i<31):
    print(i,'.',title_from_index)
    i+=1

"""# Get all movies based on recommendation score wrt favourite movie"""

Movie_name=input('Enter the movie name:')
list_of_all_titles=df['Movie_Title'].tolist()
Find_close_match=difflib.get_close_matches(Movie_name, list_of_all_titles)
Close_Match=Find_close_match[0]
Index_of_Movie=df[df.Movie_Title==Close_Match]['Movie_ID'].values[0]
Recom_score=list(enumerate(c[Index_of_Movie]))
Sorted_similar_movies=sorted(Recom_score,key=lambda x:x[1] ,reverse=True)
print("Top 10 movies suggested to you:")
i=1
for movie in Sorted_similar_movies:
  index=movie[0]
  title_from_index=df[df.Movie_ID==index]['Movie_Title'].values
  if (i<11):
    print(i,'.',title_from_index)
    i+=1

"""# Explaination

In this project we are recommending the user a movie based upon his entry where we used cosine similarity measure to find the similar movies based upon the selected entries like Movie_Genre','Movie_Keywords','Movie_Spoken_Language','Movie_Production_Country','Movie_Cast'.We are using difflib to compare data within the dataset and retreiving the recommendation score and based upn the score we are classifying the movies and returning the top 10 movies.
"""